### ISSUE TITLE
INFOGRAFIA DE HILOS EN C#

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/infografia-de-hilos-Valentiin01#2]
[Infografia_Genaro Santiago Valentin.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Valentiin01/files/6517358/Infografia_Genaro.Santiago.Valentin.pdf)

**Comment by garaudy12** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
